baseURL: "https://amathews.com"
languageCode: "en-us"
title: "AndyMathews"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "AndyMathews"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/brandlogo-dark.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "AndyMathews" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Andy."
    subtitle: "I help bring content to global audiences"
    content: "Media localization specialist and team lead. I’m continuously developing new localization solutions to make content accessible, immersive, and enjoyed worldwide."
    image: /images/office_2.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "CV"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-youtube
          url: https://youtu.be/wo4P_YL4z9M
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/andymathewsmartin/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/office_2.jpg"
    content: |-
        I am a localization specialist with a focus on vendor and project management for Netflix-commissioned subtitles. I have a background in translation, teaching, and copywriting, and I have a profound interest in workflow streamlining and optimization. I am currently working as DTT Partner Lead at Transperfect Media.
    
    skills:
      enable: true
      title: "Here are a few of my skills:"
      items:
        - "Linguistics"
        - "Timed Text"
        - "Productivity Software"
        - "Video Editing"
        - "Data Analytics"
        - "Teaching"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Account Manager and Team Lead Netflix DTT Partner Program"
        company: "TransPerfect Media"
        companyUrl: "https://www.transperfect.com/media"
        date: "Jan 2019 - present"
        featuredLink:
          enable: true
          name: "View DTT Program"
          url: "http://gvm.netflixstudios.com/"
        content: |-
          I am currently working as an account manager and team lead at [TransPerfect Media (formerly Sublime Subtitling)](https://www.transperfect.com/media) in Madrid, Spain. I am currently leading a team in charge of training and managing a pool of 200 + linguists who fulfill Netflix-commissioned timed text projects.
          - Account Manager and Team lead: Drove strategy and client engagement for Netflix Direct Timed Text projects, ensuring client satisfaction and enhancing project volume and revenue by 77.26% average YoY.
          - Recruitment: Developed scalable eLearning courses, cutting onboarding time in half and growing our linguist pool by 900%, expanding language coverage to 20+ languages.
          - Operations: Innovated 6 project management and quality assurance protocols, enhancing team productivity and readiness for scaling up as needed, and slashing department costs by at least 40%.
          - KPI analysis: Lead strategy to consistently meet Netflix's KPI milestones in On-time Delivery rate, Objective Errors Per Subtitle Event, and Subtitle Redelivery Request rate.
          
      - job: "Localization Project Manager"
        company: "Sublime Subtitling"
        companyUrl: "https://www.sublimesubtitling.com/"
        date: "May 2018 - Dec 2018"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: Production Department
        content: |
          - Production Department
            - Oversaw the life-cycle of multilingual text and AV translation projects for a variety of clients, content types, and project scopes, ensuring quality and TAT were met.
            - Conducted quality checks and gave feedback.
          - Vendor Management Team Department
            - Helped develop scalable solutions for vetting and ranking over 300 linguists in various languages.
            - Helped Sublime meet ISO standards to remain competitive and drive new business.

      - job: "AV Subtitler/Translator/QCer"
        company: "Freelance"
        companyUrl: ""
        date: "Jul 2017 - May 2018"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Worked on over 5000 minutes of high-profile subtitling projects, meeting quality and delivery standards for several clients/LSPs. Flexible in undertaking complex requests with sudden changes in scope and workflow.
          - Language Pairs: EN>ES, ES>EN (Castillian and Latam ES)
          - Roles: Language Template Authoring and QC, Subtitle Authoring and QC, SDH/CC Authoring and QC
          - Software: EZTitles, OOONA
          - Specs: Netflix, Amazon, RedBull, Custom

      - job: "ESL Teacher"
        company: "Escuelas Católicas Madrid"
        companyUrl: "https://www.ecmadrid.org/es/programas/programa-beda"
        date: "December 2015 - Jul 2017"
        featuredLink:
          enable: true
          url: "https://www.colegiosanagustin-madrid.org/"
        content: |
          Planned and delivered full lessons for 18 classes at a top-ranked school in Madrid. Integrated technology, music, and drama to keep it engaging and fun Integrated technology, music, and drama to keep lessons engaging and fun, resulting in a general improvement in students' grades and attitudes toward learning a second language.

      - job: "Floor Supervisor/Marketing Assistant"
        company: "Project 219 Café"
        companyUrl: "https://www.facebook.com/importersofhardware/?locale=es_LA"
        date: "Sep 2013 - Mar 2014"
        content: "As the dynamic manager of a rising café in Melbourne's CBD, I juggled roles from Floor Supervisor to Cook and Marketer. I efficiently managed service floors, organized events, and handled daily café operations. Learned culinary skills as I executed and then created recipes and prepared dishes. On the marketing front, I led our social media efforts, developed promotions, and crafted menus. My initiative also brought to life a cocktail bar in the basement"

      - job: "EN<>ES Translator"
        company: "Freelance"
        companyUrl: ""
        date: "Jan 2018 - May 2018"
        content: "Under my father's tutelage, and having grown up bilingual in Spanish and English, I learned and perfected the translation trade. My work spanned translating diverse materials, from magazine features and columns to technical guides and legal papers, showcasing my versatility and linguistic proficiency."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
